/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SprintSummaryRouteImport } from './routes/sprint-summary'
import { Route as IndexRouteImport } from './routes/index'

const SprintSummaryRoute = SprintSummaryRouteImport.update({
  id: '/sprint-summary',
  path: '/sprint-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sprint-summary': typeof SprintSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sprint-summary': typeof SprintSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sprint-summary': typeof SprintSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sprint-summary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sprint-summary'
  id: '__root__' | '/' | '/sprint-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SprintSummaryRoute: typeof SprintSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sprint-summary': {
      id: '/sprint-summary'
      path: '/sprint-summary'
      fullPath: '/sprint-summary'
      preLoaderRoute: typeof SprintSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SprintSummaryRoute: SprintSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
